# Generated by Django 6.0.1 on 2026-01-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('mood', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('normal', 'Обычное'), ('bad', 'Плохое'), ('sick', 'Болеет')], max_length=20, verbose_name='Настроение/Состояние')),
                ('ate_well', models.BooleanField(default=True, verbose_name='Хорошо покушал')),
                ('slept_well', models.BooleanField(default=True, verbose_name='Хорошо спал')),
                ('participated', models.BooleanField(default=True, verbose_name='Активно участвовал')),
                ('activities', models.TextField(blank=True, verbose_name='Чем занимался')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации родителям')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Заметки воспитателя')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Температура')),
                ('medicine_taken', models.TextField(blank=True, verbose_name='Принятые лекарства')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='children.child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Запись в дневнике',
                'verbose_name_plural': 'Записи в дневнике',
                'ordering': ['-date'],
            },
        ),
    ]
