# Generated by Django 6.0.1 on 2026-01-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('age_range', models.CharField(choices=[('1.5-3', '1.5-3 года (Ясельная)'), ('3-4', '3-4 года (Младшая)'), ('4-5', '4-5 лет (Средняя)'), ('5-6', '5-6 лет (Старшая)'), ('6-7', '6-7 лет (Подготовительная)')], max_length=20, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
                ('teacher', models.CharField(max_length=100, verbose_name='Воспитатель')),
                ('teacher_photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='Фото воспитателя')),
                ('group_photo', models.ImageField(blank=True, upload_to='groups/', verbose_name='Фото группы')),
                ('capacity', models.IntegerField(default=15, verbose_name='Вместимость')),
                ('occupied', models.IntegerField(default=0, verbose_name='Заполнено')),
                ('has_creative', models.BooleanField(default=True, verbose_name='Творческие занятия')),
                ('has_sports', models.BooleanField(default=True, verbose_name='Спортивные занятия')),
                ('has_music', models.BooleanField(default=True, verbose_name='Музыкальные занятия')),
                ('has_english', models.BooleanField(default=False, verbose_name='Английский язык')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Бассейн')),
                ('schedule', models.TextField(blank=True, verbose_name='Расписание дня')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
