# Generated by Django 6.0.1 on 2026-01-15 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='has_english',
        ),
    ]
