# Generated by Django 6.0.1 on 2026-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя родителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('child_age', models.CharField(blank=True, choices=[('', 'Не указано'), ('1.5-3', '1.5-3 года'), ('3-4', '3-4 года'), ('4-5', '4-5 лет'), ('5-6', '5-6 лет'), ('6-7', '6-7 лет')], max_length=10, verbose_name='Возраст ребенка')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
