# Generated by Django 6.0.1 on 2026-01-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='child_group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='child_name',
        ),
    ]
