# Generated by Django 6.0.1 on 2026-01-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('contract', 'Договор'), ('application', 'Заявление'), ('rules', 'Правила'), ('schedule', 'Расписание'), ('menu', 'Меню'), ('payment', 'Оплата')], max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='parents/documents/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Документ для родителей',
                'verbose_name_plural': 'Документы для родителей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('health', 'Здоровье ребенка'), ('education', 'Воспитание и развитие'), ('adaptation', 'Адаптация к саду'), ('nutrition', 'Питание'), ('safety', 'Безопасность')], max_length=50, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parents/tips/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Совет для родителей',
                'verbose_name_plural': 'Советы для родителей',
                'ordering': ['-created_at'],
            },
        ),
    ]
